name: WebdriverIO Android Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_APP_ID: ${{ secrets.BROWSERSTACK_APP_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run WebdriverIO tests (Google Pixel)
        run: npx wdio wdio.pixel.conf.js

      - name: Install Allure globally
        run: npm install -g allure-commandline

      - name: Generate Allure report
        run: npx allure generate reports -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main-repo/allure-report
          publish_branch: allure-report
